### ISSUE TITLE
Invalid AMP pages caused by dnt_config script tag and the Automattic AMP plugin

### ISSUE THREAD

**Issue by 16patsle** [futtta/wp-donottrack#1]
My Google Search Console recently started complaining about a line like this, which somehow was kept even on the AMP version of my site.
```html
<script type="text/javascript">var dnt_config={ifdnt:"0",mode:"blacklist",black:["media6degrees.com","quantserve.com","lockerz.com"],white:[]};</script>
```
Is there something that can be done about this, so that the AMP plugin automatically filters it, like it does with all the other scripts? Or would it be something the AMP plugin needs to handle?

[Relevant part of this plugin](https://github.com/futtta/wp-donottrack/blob/master/wp-donottrack.php#L90)
[AMP plugin by Automattic](https://github.com/Automattic/amp-wp)
[German article describing the same issue](https://nextlevelseo.de/wp-donottrack-verhindert-amp-7112/)

**Comment by futtta** [comment]
can you check [that commit](https://github.com/futtta/wp-donottrack/commit/944db36e60a46808ae9bd45c465e678a0b97b84b) (or the full zipfile) @16patsle ?

**Comment by 16patsle** [comment]
That was fast! Seems like it's working great now. Replaced the plugin on my site, and the AMP version seems correct. Ran it through the validator, and seemed to be valid now.
