### ISSUE TITLE
Option names

### ISSUE THREAD

**Issue by lukas-mika** [futtta/wp-donottrack#2]
Hey,
thank you thousand times for this great plugin!

May I still rise a (tiny) change request?
Due to the fact, that WP's option API does not use the option IDs but rather their names as identifiers, there is the possibility that option names conflict.
Having option names such as 'blacklist' or 'whitelist' is therefore very likely to collide with other options (which happened with a custom sandbox plugin in my case).
Could you please prefix the option names with for example 'wpdnt_', so that you make them more unique?

I already tried to do it myself (especially with all the 'get_option()' calls), but I wasn't able to figure out where in your source the options get updated in the backend. I _guess_ it happens in `options.php` using the variable names, but I wasn't sure enough.
If you point me to the right spots, I'm happy to provide a pull request :)

Cheers!

**Comment by futtta** [comment]
the options indeed get written from options.php based on the form id/ name in the HTML in there. and you're right, the options should be pre-pended, so if you create a PR I'll be happy to merge! :-)

frank

**Comment by lukas-mika** [comment]
Hey there,

just added PR https://github.com/futtta/wp-donottrack/pull/3. It has been quite some work to refresh, enhance and optimize some of your coding, but I think it's been quite a cool result.

Check it out ;)

Do you have some (manual) test cases at hand, to do the testing? Especially "SuperClean mode" should be tested for both PHP 5.5 and PHP 7.2.

If you have any questions about my PR, feel free to contact me.

Cheers!
