### ISSUE TITLE
integration with Complianz

### ISSUE THREAD

**Issue by rlankhorst** [futtta/wp-donottrack#7]
Hi @futtta, 

I'm developing a plugin which has a partial overlap with yours: cookie banner with consenting to third party cookies/tracking (wordpress.org/complianz-gdpr). I see you have a more js minded approach, which seems interesting. I was thinking to adjust the plugin so it integrates smoothly with yours. I already encountered some users who were using both plugins on their website. Is there a javascript hook I can execute on cookie acceptance?

Thanks and merry Christmas ;)

Rogier

**Comment by futtta** [comment]
Middag Rogier;
There's no hook, but you could set a cookie to confirm people are OK with being tracked, as per [this WPDNT FAQ entry](https://wordpress.org/plugins/wp-donottrack/#how%20can%20i%20make%20my%20users%20choose%20not%20to%20be%20tracked%20and%2For%20integrate%20with%20civic%20cookie%20control%3F)?

Feestelijke groeten uit België!
frank

**Comment by rlankhorst** [comment]
Thanks, I'll add a dont_track_me cookie, then on consent can set it to false. I'm thinking on proposing a wp core feature which allows plugins and themes to set or request cookie consent info in WordPress. Might be a good way to standardize these integrations. 

Hartelijk dank :)

**Comment by rlankhorst** [comment]
@futtta the plugins are now fully compatible as of the latest update. :)

**Comment by futtta** [comment]
great job! ::-)
